before:
  hooks:
    - go mod tidy
gomod:
  proxy: true
dist: results
builds:
  - env: ["CGO_ENABLED=0"]
    goos: ["linux", "windows", "darwin"]
    flags: ["-trimpath"]
    ldflags: ["-s -w"]
    targets: ["go_first_class"]
    mod_timestamp: '{{ .CommitTimestamp }}'
checksum:
  name_template: 'checksums'
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: '${artifact}.pem'
    stdin: '{{ .Env.COSIGN_PWD }}'
    args:
      - sign-blob
      - '--key=$COSIGN_KEY'
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - '--yes'
    artifacts: checksum
    output: true
sboms:
  - artifacts: archive
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Other work'
      order: 999
