# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
# Build for all first-class targets
builds:
  - env: ["CGO_ENABLED=0"]
    goos: ["linux", "windows", "darwin"]
    flags: ["-trimpath"]
    ldflags: ["-s -w"]
    targets: ["go_first_class"]
    mod_timestamp: '{{ .CommitTimestamp }}'
# Non-Linux OS like Windows prefer a file extension
checksum:
  name_template: 'checksums.txt'
# Split formats for different OS requirements
archives:
  - format: tar.gz
    # This name template makes the OS and Arch compatible with the results of uname.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # Use zip for Windows archives
    format_overrides:
    - goos: windows
      format: zip
# Also bundle sources
#source:
#  enabled: true
# Creates SBOMs of all archives and the source tarball using syft
# https://goreleaser.com/customization/sbom
sboms:
  - artifacts: archive
  - id: source # Two different sbom configurations need two different IDs
    artifacts: source
# Name snapshot version 'next'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
# Generate changelog from conventional commits
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Other work'
      order: 999
