name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build CI Tool
        working-directory: ./ci
        run: go build
      - name: Run Tests
        run: ./ci/ci test
  race:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build CI Tool
        working-directory: ./ci
        run: go build
      - name: Run Race Detector
        run: ./ci/ci test --race
  coverage:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build CI Tool
        working-directory: ./ci
        run: go build
      - name: Run Coverage Reporter
        run: ./ci/ci test --cover
      - name: Upload Report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: results/cover.out
